---
- name: "Безопасная подготовка SSH-ключей"
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Сканирование и добавление отпечатков хостов в known_hosts"
      ansible.builtin.known_hosts:
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
        path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        state: present
      loop:
        - "192.168.56.130"
        - "192.168.56.135"
        - "192.168.56.140"

- name: "Базовая настройка операционной системы"
  hosts: all
  become: true
  roles:
    - common

- name: "Развертывание сети WireGuard VPN"
  hosts: all
  become: true
  roles:
    - wireguard

- name: "Развертывание гибридного кластера K3s"
  hosts: k3s_master,k3s_worker
  become: true
  roles:
    - k3s

- name: "Настройка серверов приложений (Docker-окружение)"
  hosts: app
  become: true
  roles:
    - app

- name: "Настройка CI/CD сервера Jenkins"
  hosts: jenkins
  become: true
  roles:
    - jenkins

- name: "Настройка отказоустойчивого кластера БД (Patroni)"
  hosts: database
  become: true
  roles:
    - database

- name: "Настройка сервера мониторинга"
  hosts: monitoring
  become: true
  roles:
    - monitoring
