---
- name: Подготовка SSH-ключей безопасности
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Безопасное сканирование отпечатков виртуалбоксов
      ansible.builtin.known_hosts:
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
        path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        state: present
      loop:
        - "192.168.56.130"
        - "192.168.56.135"
        - "192.168.56.140"

- name: Common setup for all servers
  hosts: all
  become: true
  roles:
    - common

- name: Setup WireGuard VPN on all nodes
  hosts: all
  become: true
  roles:
    - wireguard

- name: Setup App Server
  hosts: app
  become: true
  roles:
    - app

- name: Setup Jenkins Server
  hosts: jenkins
  become: true
  roles:
    - jenkins

- name: Setup Database Servers
  hosts: database
  become: true
  roles:
    - database

- name: Setup Monitoring Server
  hosts: monitoring
  become: true
  roles:
    - monitoring
