all:
  children:

    # ── AWS серверы ──────────────────────
    aws:
      children:

        app:
          hosts:
            app_server:
              ansible_host: 3.21.5.210
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/fitflow
              wireguard_ip: 10.8.0.1

        jenkins:
          hosts:
            jenkins_server:
              ansible_host: 18.225.100.178
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/fitflow
              wireguard_ip: 10.8.0.2

    # ── Локальные VM (VirtualBox) ────────
    local_vms:
      children:

        database:
          hosts:
            pg_master:
              ansible_host: 10.219.78.157
              ansible_user: first-vm
              ansible_ssh_private_key_file: ~/.ssh/fitflow
              wireguard_ip: 10.8.0.3
            pg_replica:
              ansible_host: 10.219.78.107
              ansible_user: new3
              ansible_ssh_private_key_file: ~/.ssh/fitflow
              wireguard_ip: 10.8.0.4

        monitoring:
          hosts:
            monitoring_server:
              ansible_host: 10.219.78.135
              ansible_user: aisha
              ansible_ssh_private_key_file: ~/.ssh/fitflow
              wireguard_ip: 10.8.0.5