server {
    listen 80;
    server_name localhost;

    # Указываем DNS-сервер Кубера (K3s), чтобы резолвить имена на лету
    resolver 10.43.0.10 valid=5s;

    # Отдаём статику фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Проксируем запросы к API
    location /api/ {
        # Скрываем адрес в переменную с полным DNS-именем внутри кластера
        set $backend_api "http://cluster.local";
        
        proxy_pass $backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Проксируем Swagger документацию
    location /docs {
        set $backend_docs "http://cluster.local/docs";
        
        proxy_pass $backend_docs;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        set $backend_json "http://cluster.local/openapi.json";
        
        proxy_pass $backend_json;
    }
}
