apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitflow-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitflow-frontend
  template:
    metadata:
      labels:
        app: fitflow-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ip-10-0-1-127
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - "sh"
            - "-c"
            - |
              echo "DevOps: Ожидаю запуска и DNS-разрешения сервиса бэкенда (api:8000)..."
              until nc -zv api 8000; do
                echo "DevOps: Бэкенд еще не доступен. Ожидание 2 секунды..."
                sleep 2
              done
              echo "DevOps: Бэкенд успешно ответил! Разрешаю запуск основного контейнера Nginx."
      containers:
        - name: frontend
          image: aisharust94/fitflow-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

